[package]
name = "cce-ui"
version = "0.1.0"
edition = "2021"

[lib]
name = "cce_ui"
path = "src/lib.rs"

[dependencies]
raw-window-handle = "0.6"
wgpu = "24"
glam = "0.29"
bytemuck = { version = "1", features = ["derive"] }
pollster = "0.4"
glyphon = "0.8"
tokio = { version = "1", features = ["full"] }
smithay-client-toolkit = { version = "0.19.2", features = ["calloop"] }
calloop = "0.13.0"
calloop-wayland-source = "0.3.0"
wayland-client = { version = "0.31", features = ["system"] }
wayland-protocols = { version = "0.31", features = ["client", "unstable"] }
wayland-backend = "0.3"
wayland-scanner = "0.31"
bitflags = "2"
xkeysym = "0.2"
resvg = "0.41.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
kdl = "4.6"
libc = "0.2"
log = "0.4"
rfd = "0.15"


