pub mod button;
pub mod checkbox;
pub mod slider;
pub mod slider2d;
pub mod spinbox;
pub mod color_selector;
pub mod dropdown;
pub mod text_box;
pub mod trackpad;
pub mod font_selector;
pub mod button_strip;
pub mod keybind_recorder;
pub mod ramp;

pub use button::{Button, ButtonKind, PageButton};
pub use checkbox::{Checkbox, Toggle};
pub use slider::{Slider, RangeSlider, ActiveThumb};
pub use slider2d::Slider2D;
pub use spinbox::Spinbox;
pub use color_selector::ColorSelector;
pub use dropdown::Dropdown;
pub use text_box::{TextBox, get_font_db};
pub use trackpad::{Trackpad, Finger};
pub use font_selector::FontSelector;
pub use button_strip::ButtonStrip;
pub use keybind_recorder::KeybindRecorder;
pub use ramp::{Ramp, RampKey, ColorRamp, ColorRampKey, format_ramp_spec, parse_ramp_spec};

pub const BREADCRUMB_PADDING: f32 = 8.0;
pub const SEGMENT_GAP: f32 = 4.0;
